- name: "install firewalld"
  apt: name=firewalld state=present
  when: ansible_os_family == "Debian"

- name: "be sure firewalld is installed"
  yum: name=firewalld state=installed
  when: ansible_os_family == "RedHat"

- name: "be sure firewalld is disabled"
  systemd: name=firewalld enabled=no

- name: "be sure iptables is disabled"
  systemd: name=iptables enabled=no
  ignore_errors: yes

- name: "be sure firewalld is stopped"
  systemd: name=firewalld state=stopped
  ignore_errors: yes

- name: "be sure iptables is stoppped"
  service: name=iptables state=stopped
  ignore_errors: yes

- name: "Remove swapfile from /etc/fstab"
  mount:
    name: swap
    fstype: swap
    state: absent

- name: "Disable swap"
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: "Changing perm of /etc/rc.local +x"
  file:
   dest: /etc/rc.local
   mode: a+x