- name: "[keepalibed] - kubernetes check_apiserver.sh"
  template:
   src: ../templates/check_apiserver.sh
   dest: /etc/keepalived/check_apiserver.sh
   owner: root
   group: root
   mode: 0755
  when: inventory_hostname in groups['master']

- name: "[keepalibed] - kubernetes keepalvied.conf"
  template:
   src: ../templates/keepalived.conf.j2
   dest: /etc/keepalived/keepalived.conf
   owner: root
   group: root
   mode: 0644
   backup: yes
  when: inventory_hostname in groups['master']

- name: "[keepalived] - enable service"
  systemd:
    name: keepalived
    enabled: yes
  when: inventory_hostname in groups['master']

- name: "[keepalived] - start service"
  service:
   name: keepalived
   state: started
  when: inventory_hostname in groups['master']

