- name: "[destroy] - destroy kubernetes"
  shell: |
   kubeadm reset -f
  ignore_errors: True

- name: "[destroy] - destroy pki.tgz"
  shell: |
   rm -rf /etc/kubernetes/pki.tgz
  delegate_facts: True
  delegate_to: "{{ groups['master'][0] }}"
  ignore_errors: True

- name: "[destroy] - destroy etcd"
  shell: |
   docker rm etcd -f
   rm -rf {{ etcd }}/docker-etcd.sh
   docker rm $(docker ps -qa) -f
   rm -rf {{ etcdstorage }}/*
   rm -rf /var/lib/etcd/*
  delegate_to: "{{ item }}"
  with_items:
   - "{{ groups['etcd'] }}"
  ignore_errors: True

- name: "[destroy] - stopped service"
  service:
   name: keepalived
   state: stopped
  ignore_errors: True
  when: inventory_hostname in groups['master']
